# Generated by Django 5.2.5 on 2025-08-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='courses',
            new_name='course',
        ),
    ]
